v0.9 release

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8,13 +8,16 @@
 #			This is not about auto magic compiling,
 #			this is about simply placing files.
 #
+#	Path Reference:	http://www.pathname.com/fhs/
+#
+#
 #	To report bugs or suggestions, please raise an issue on:
 #			https://github.com/sri-arjuna/yassi/issues
 #
 #	Created:	2015.07.27
-#	Changed:	2015.08.10
+#	Changed:	2015.08.16
 	script_name=configure
-	script_version=0.8
+	script_version=0.9
 #
 # ------------------------------------------------------------------------
 #
@@ -62,7 +65,7 @@
 			APP="projectname"
 			BINDIR=bin
 			DOCDIR="docs/README.md docs/COPYING"
-			#MAN1DIR=docs/man1
+			#MAN1DIR=docs/man1/\*.1
 			#INFODIR=tex/\$APP.info
 			DATADIR="./templates ./extra"
 			ISSUE="https://github.com/sri-arjuna/yassi/issues"
@@ -88,9 +91,9 @@
 			# A plain filename will copy just the file
 			# The $APP.{info,html} files will be generated by the PRIOR[1|2] array entry.
 			# Multiple entries shall be quoted.
-			DOCDIR="docs/README.md docs/COPYING tex/\$APP.html"
+			DOCDIR="docs/README.md docs/COPYING docs/tex/\$APP.html"
 			MAN1DIR=docs/man1
-			INFODIR=tex/\$APP.info
+			INFODIR=docs/tex/\$APP.info
 			# A dirname with a leading ./ will copy the directory
 			DATADIR="./templates ./themes"
 			
@@ -106,18 +109,24 @@
 			PRIOR[0]="texi2any -o docs/tex/\$APP.info --no-split docs/tex/\$APP.texi"
 			PRIOR[1]="texi2any --html -o docs/tex/\$APP.html --no-split docs/tex/\$APP.texi"
 			
-			# Do things before copying/installing
+			# Do things after copying/installing
 			POST[0]=post_script1.sh
 			POST[1]="echo \"Thank you for choosing '\$APP'!\""
 			
 			# Append this in the uninstall script.
-			REMOVE[0]="echo \"Dare you remove \$APP!\""
+			REMOVE[0]="rm docs/tex/\$APP.html docs/tex/\$APP.info"
+			REMOVE[1]="echo \"Dare you remove \$APP!\""
 		EOF
 		exit 0
 	}
 	show_help() {
 	# Prints the helpscreen
 	# and exits
+		MSG_TR_CONTACT_INFO="
+	$( [ ! -z "$BUGS" ] && echo "Report bugs of \"$APP\"-installation to \"$BUGS\"")
+	$( [ ! -z "$ISSUE" ] && echo "Report bugs of \"$APP\"-installation on \"$ISSUE\"")
+"	
+		
 		MSG_TR_HELP="Usage:	./$script_name [options]
 Routine to configure the installation of $APP $APP_VER
 
@@ -127,7 +136,7 @@ Options:
 	--sample		Prints a sample configure.cfg required by projects
 	--sample-full		Prints a sample configure.cfg required by projects
 	
-	--tarball		Configures ${APP:-APPNAME} and saves the folder as tarball
+	--tarball		Configures ${APP:-APPNAME}, runs PRIOR tasks and saves the folder as tarball
 	--prefix DIR		Sets the prefix to DIR		(default: ${APP_DIR:-/usr/local})
 	
 	--bindir DIR		user executeables 		(\$PREFIX/bin)
@@ -152,9 +161,7 @@ Options:
 	
 	--sharedstatedir	modifiable architecture-independent	(\$PREFIX/com)
 			
-	$( [ ! -z "$BUGS" ] && echo "Report bugs of \"$APP\" to \"$BUGS\"")
-	$( [ ! -z "$ISSUE" ] && echo "Report bugs of \"$APP\" on \"$ISSUE\"")
-	"
+	$MSG_TR_CONTACT_INFO"
 		echo "$MSG_TR_HELP"
 		exit 99
 	}
@@ -249,19 +256,19 @@ Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 					"set -x" >> "make-$m"
 			chmod +x "make-$m"
 		done
-		>"$REFERENCE"
+		echo "prefix=${FHS[prefix]}">"$REFERENCE"
 		
 		# Write content of PRIOR tasks, if any
 		if [ ! -z "$(echo ${PRIOR[@]})" ]
 		then	C=0
 			echo >> "make-install"
 			while [ ! -z "${PRIOR[$C]}"  ]
-			do 	echo "${PRIOR[$C]} || exit 1" >> "make-install"
+			do 	echo "${PRIOR[$C]}" >> "make-install" # || exit 1"
 				((C++))
 			done
 		fi
 		
-		# Search for the available variables
+		# Search for the available/used variables
 		for index in $variable_list
 		do	# Expand index
 			tmp="${!index}"
@@ -288,6 +295,7 @@ Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 				esac
 			fi
 		done
+		. "$REFERENCE"
 		
 		# Check for removal operations
 		if [ ! -z "$(echo ${REMOVE[@]})" ]
@@ -297,8 +305,8 @@ Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 			while 	item="${REMOVE[$C]}"
 				[ ! -z "$item" ]
 			do 	[ -f "$item" ] && \
-					echo "sh ./$item || exit 1" >> "make-uninstall" || \
-					echo "$item || exit 1" >> "make-uninstall"
+					echo "sh ./$item" >> "make-uninstall" || \
+					echo "$item" >> "make-uninstall" #  || exit 1
 				((C++))
 			done
 		fi
@@ -310,12 +318,6 @@ Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 			echo "mkdir -p ${FHS[sysconfdir]} ; cp \"$REFERENCE\" \"${FHS[sysconfdir]}/$APP.conf\"" >> "make-install"
 			echo "rm -f ${FHS[sysconfdir]}/$APP.conf" >> "make-uninstall"
 		fi
-		for m in install uninstall
-		do	echo >> "make-$m"
-			printf '%s\n' \
-				"RET=\$?" \
-				"set +x" >> "make-$m"
-		done
 		
 		# Check for post operations, letter better here, than with 'set -s'
 		if [ ! -z "$(echo ${POST[@]})" ]
@@ -324,13 +326,20 @@ Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 			while 	item="${POST[$C]}"
 				[ ! -z "$item" ]
 			do 	[ -f "$item" ] && \
-					echo "sh ./$item || exit 1" >> "make-install" || \
-					echo "$item || exit 1" >> "make-install"
+					echo "sh ./$item" >> "make-install" || \
+					echo "$item" >> "make-install" # || exit 1
 				((C++))
 			done
 		fi
 		
-		echo "echo;echo \"Finished installation of $APP with exit code: \$RET (0=success)\"" >> "make-install"
+		for m in install uninstall
+		do	echo >> "make-$m"
+			printf '%s\n' \
+				"RET=\$?" \
+				"set +x" >> "make-$m"
+		done
+		
+		echo "echo;echo \"Finished installation of $APP\";exit \$RET" >> "make-install"	# with exit code: \$RET (0=success)\""
 	}
 #
 #	Get options
@@ -402,10 +411,14 @@ Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 		[ -z "$APP_VER" ] && \
 			VERSION="" || \
 			VERSION="_${APP_VER}"
+		./configure --prefix=${FHS[prefix]}
+		source "$REFERENCE"
+		for t in "${PRIOR[@]}"
+		do 	(set -x ; $t )
+		done
 		tarball="../${APP}$VERSION.tar.gz"
-		tar -acf "$tarball" *
-		mv "$tarball" . && \
-			echo "Successfully created tarball ${tarball##*/}!"
+		tar -acf "$tarball" * && \
+			echo "Successfully created tarball ${tarball}!"
 	else	echo
 		echo "The installation script has been configured to ${FHS[prefix]}."
 		echo "To install \"$APP\" now, please execute: su -c \"./make-install\""
