Updated YASSI and 'manual installation using itself'

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3,7 +3,7 @@
 # ------------------------------------------------------------------------
 #
 #	Created:	2015.07.27
-#	Changed:	2015.09.05
+#	Changed:	2015.09.09
 	script_name=configure
 	script_version=0.9.6
 #
@@ -45,26 +45,38 @@
 #
 # ------------------------------------------------------------------------
 #
-#	Internal Variables
+#	Configfile / Option defaults
 #
-	unset FHS POST PRIOR REMOVE
-	declare -A FHS
-	declare -a POST
-	declare -a PRIOR
-	declare -a REMOVE
-	
 	APP=""
+	APP_VER=""
+	APP_REQUIRES=""
+	CFG_REQUIRES=""
+	BUGS=""
+	ISSUE=""
 	doRef=false
 	doTarball=false
 	is_at_home=false
-	SOURCE="./$script_name.cfg"
-	#LOG="${PWD:-$(pwd)}/make-install.log"		# Not yet used, see lines 214 + 215 for most important application
+#
+#	Internal Variables
+#
+	unset FHS PREPARE PRIOR POST REMOVE
+	declare -A FHS
+	declare -a PREPARE	# This will be ran during ./configure --prefix=/usr
+	declare -a PRIOR	# This will be ran first during ./make-install
+	declare -a POST		# This will be ran last during ./make-install
+	declare -a REMOVE	# This will be ran during ./make-uninstall
+	declare -a CLEAN	# This will be ran during ./make-distclean
+	AWK=\awk
+	GREP=\grep
+	SED=\sed
+	CONFIG="./$script_name.cfg"
 	install_prefix="sudo "
-	
+	#LOG="${PWD:-$(pwd)}/make-install.log"		# Not yet used, see lines 214 + 215 for most important application
 	mandirs="$(echo man{1..9}dir)"
 	index_list="prefix bindir sbindir sysconfdir datarootdir datadir docdir htmldir infodir $mandirs compldir sharedstatedir localstatedir"
 	variable_list="";for i in $index_list;do variable_list+=" ${i^^}";done
-	source "$SOURCE"
+	TMP="$PWD/tmp.$$"
+	source "$CONFIG"
 #
 #	Functions
 #
@@ -75,26 +87,26 @@
 		#
 		#	Project Info
 		#
-			APP=projectname
-			APP_REQUIRES="awk bash grep sed"
+		 	APP=projectname
+		 	APP_REQUIRES="awk bash grep sed"
 		#
 		#	Targets
 		#
-			BINDIR=bin
-			DOCDIR=docs/[A-Z]*
-			MAN1DIR=docs/man/\*.1
-			INFODIR=docs/info/\*.info
-			DATADIR="./templates ./extra"
+		 	BINDIR=bin
+		 	DOCDIR=docs/[A-Z]*
+		 	MAN1DIR=docs/man/\*.1
+		 	INFODIR=docs/info/\*.info
+		 	DATADIR="./templates ./extra"
 		#
 		#	Contact
 		#
-			BUGS="$USER AT $HOSTNAME"
-			ISSUE="https://github.com/sri-arjuna/yassi/issues"
+		 	BUGS="$USER AT $HOSTNAME"
+		 	ISSUE="https://github.com/sri-arjuna/yassi/issues"
 		EOF
 		exit 0
 	}
 	show_sample_full() {
-	# Prints a sample configure.cfg
+	# Prints an advanced sample configure.cfg
 	# and exits
 		cat <<-EOF
 		#
@@ -103,44 +115,61 @@
 		 	# Used for /usr/share/\$APP & /usr/share/doc/\$APP
 		 	APP=projectname
 		 	APP_REQUIRES="awk bash grep sed"
+		 	CFG_REQUIRES="texi2any txt2man"
+		 	
 		 	# Used for helpscreen & tarball
 		 	APP_VER=0.1
-		 	# If set, overwrites /usr/local for plain './configure' invocation
-		 	APP_DIR=~/.local
+		 	
+		 	# If set, overwrites the default PREFIX (/usr/local) to assigned value.
+		 	#APP_DIR=~/.local
+		 	
+		 	# Set true to install the reference file to $PREFIX/$SYSCONFDIR/\$APP.conf
+		 	# This will automaticly be uninstalled if set to true, no extra work.
+		 	#doRef=false
 		#
-		#	Targets
+		#	Prepare, before making a tarball
+		#	So the CFG_REQUIRES are only needed on one machine, and the tarball then can be shared 
+		#
+		 	PREPARE[0]="texi2any -o docs/info/\$APP.info --no-split docs/info/\$APP.texi"
+		 	PREPARE[1]="texi2any --html -o docs/info/\$APP.html --no-split docs/info/\$APP.texi"
+		 	PREPARE[2]="which tuirc 1>/dev/zero 2>/dev/zero || git clone https://github.com/sri-arjuna/tui tui"
+		 	PREPARE[3]="bin/\$APP --help | txt2man -T \${APP^^} -r \$APP_VER > docs/man/\$APP.1"
+		#
+		#	Tasks prior to installation, but after tarball
+		#
+		 	# Only install if the current system does not provide TUI
+		 	PRIOR[0]="! which tuirc 1>/dev/zero 2>/dev/zero && cd tui && ./configure --prefix=${prefix} && (./make-install || make install) && cd .. "
+		#
+		#	Targets, where is what installed
 		#
 		 	BINDIR=bin
-		 	DOCDIR="docs/README.md docs/COPYING docs/tex/\$APP.html"
+		 	DOCDIR=docs/[A-Z]*
 		 	MAN1DIR=docs/man/*.1
 		 	INFODIR=docs/info/\$APP.info
-		 	DATADIR="./templates ./themes"
+		 	HTMLDIR=docs/info/\$APP.html
+		 	DATADIR="./menu ./includes"
 		#
-		#	Specials
+		#	Tasks post of installation
 		#
-			# Set true to install the reference file to /etc/\$APP.conf
-		 	doRef=false
+		 	POST[0]=scripts/post_script1.sh
+		 	POST[1]="echo \"Thank you for choosing '\$APP'!\""
+		#
+		#	Clean up what has been prepared 
+		#
+		 	CLEAN[0]="docs/info/\$APP.{info,html}"
+		 	#CLEAN[0]="docs/info/\$APP.html"
+		 	CLEAN[1]="rm docs/info/\$APP.html docs/info/\$APP.info"
+		#
+		#	Additional tasks for the uninstallation process
+		#
+		 	REMOVE[0]="tui-yesno 'Remove TUI as well?' && cd tui && \
+		 			./make-uninstall && \
+		 			./make-distclean && cd .."
 		#
 		#	Contact
 		#
 		 	BUGS="your@email.com"
 		 	ISSUE="https://github.com/sri-arjuna/yassi/issues"
-		#
-		#	Tasks prior to installation
-		#
-			# Replace ./configure with your core script
-			PRIOR[0]="./configure --help | txt2man -T \${APP^^} -r \$APP_VER > docs/man/\$APP.1"
-			PRIOR[1]="texi2any -o docs/info/\$APP.info --no-split docs/info/\$APP.texi"
-			PRIOR[2]="texi2any --html -o docs/info/\$APP.html --no-split docs/info/\$APP.texi"
-		#
-		#	Tasks post of installation
-		#
-			POST[0]=scripts/post_script1.sh
-			POST[1]="echo \"Thank you for choosing '\$APP'!\""
-		#
-		#	Additional tasks for the uninstallation process
-		#
-			REMOVE[0]="rm docs/info/\$APP.html docs/info/\$APP.info"
 		EOF
 		exit 0
 	}
@@ -154,7 +183,7 @@
 		MSG_TR_HELP="Usage:	./$script_name [options]
 Routine to configure the installation of ${APP:-APPNAME} ${APP_VER}
 
-Options:
+OPTIONS:
 	-h|--help		Shows this screen and exits
 	--version		Shows the version and exits
 	--sample		Prints a sample 'configure.cfg' required by projects and exits
@@ -178,9 +207,9 @@ Options:
 	--localstatedir		modifiable single-machine data	(\$PREFIX/var)
 	
 	--man1dir DIR		man 1 Exe & Shell commands	(\$DATAROOTDIR/man/man1)
-		2) System calls		3) Library calls	4) Special files (eg /dev)
-		5) File formats & conventions (eg: /etc/passwd)	6) Games
-		7) Miscellaneous (eg: macros, groff)		8) Root commands (sbin)
+	-	2) System calls		3) Library calls	4) Special files (eg /dev)
+	-	5) File formats & conventions (eg: /etc/passwd)	6) Games
+	-	7) Miscellaneous (eg: macros, groff)		8) Root commands (sbin)
 	--man9dir DIR		man 9 Kernel routines (non standard)	(\$DATAROOTDIR/man/man9)
 	
 	--sharedstatedir	modifiable architecture-independent	(\$PREFIX/com)
@@ -205,11 +234,20 @@ Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 	}
 	write_files() { 
 	# Write the different types of make-{distclean,install,uninstall} scripts
-	#
+	# An run pre-'make-install'-tasks
+		# Abort with failure if not all required apllication are present
+		APP_REQUIRES=""
+		source "$CONFIG";missing=""
+		for req in $CFG_REQUIRES;do
+			which $req 2>/dev/zero 1>&2 || missing+=" $req"
+		done
+		[ ! -z "$missing" ] && \
+			printf '%s\n' "Please provide these commands before configuring $APP!" "Sadly, you must figure out the package name yourself." && \
+			printf '::-->> %s\n' ${missing} && \
+			exit 1
 		write_install() { # INDEX CONTENT
 		# Prints the copy commands
 		#
-			echo "mkdir -p \"${FHS[${1,,}]}\""
 			if [ -d "$2" ] && [ ! "./" = "${2:0:2}" ]
 			then	# Its a directory, go recursive
 				echo "cp -ar \"${PWD:-$(pwd)}/$2/\"* \"${FHS[${1,,}]}\" || exit 1" | sed s,"//","/",g
@@ -231,7 +269,8 @@ Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 		write_reference() { # INDEX
 		# Prints the index reference used
 		#
-			echo "${1}=${FHS[${1,,}]}"  | sed s,"//","/",g
+			ref_val="${FHS[${1,,}]}"
+			echo "${1}=$ref_val"  | sed s,"//","/",g
 		}
 		write_uninstall() { # INDEX CONTENT
 		# Prints the remove commands
@@ -266,7 +305,7 @@ Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 		write_distclean() { 
 		# Remove the files that where created
 		#
-			echo "(sleep 0.5 ; rm -f ./make-* ; rm -f \"$REFERENCE\" ) &"
+			echo "(sleep 0.03 ; rm -f \"$REFERENCE\" ; rm -f ./make-* ; echo ) &"
 		}
 		
 		# Prepare script headers
@@ -278,8 +317,7 @@ Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 					"[ \$UID -ne 0 ] && \\" \
 					"	echo \"This script requires root access.\" && \\" \
 					"	exit 99"  >> "make-$m"
-			elif [ ! "$m" = "distclean" ]
-			then	echo "set -x" >> "make-$m"
+			else	echo "set -x" >> "make-$m"
 			fi
 			chmod +x "make-$m"
 		done
@@ -287,11 +325,15 @@ Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 		echo "prefix=${FHS[prefix]}">"$REFERENCE"
 		
 		# Write content of PRIOR tasks, if any
-		if [ ! -z "$(echo ${PRIOR[@]})" ]
-		then	C=0
+		if [ ! -z "${PRIOR[@]}" ]
+		then	source "$PWD/$REFERENCE"	# Just prefix yet
+			C=0
 			echo >> "make-install"
-			while [ ! -z "${PRIOR[$C]}"  ]
-			do 	echo "${PRIOR[$C]}" >> "make-install" # || exit 1"
+			while 	item="${PRIOR[$C]}"
+			[ ! -z "$item" ]
+			do 	[ -f "$item" ] && \
+					echo "sh ./$item" >> "make-install" || \
+					echo "$item" >> "make-install" #  || exit 1
 				((C++))
 			done
 		fi
@@ -311,6 +353,17 @@ Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 				
 				# It has content
 				write_reference "$index" >> "$REFERENCE"
+				# This is a tryout, 
+				set $index
+				# This usualy is the most important fix, sadly
+				cat >> "make-install" <<-EOF
+				tmp_str="${FHS[${1,,}]}"
+				if [ ! -d "\${tmp_str%/*}" ]
+				then 	[ -d "/usr\${tmp_str%/*}" ] && \\
+				 		ln -s "/usr\${tmp_str%/*}" "\${tmp_str%/*}" || \\
+				 		mkdir -p "\$tmp_str"
+				fi
+				EOF
 				case "$num" in
 				1)	write_install "$index" "$tmp" >> "make-install"
 					write_uninstall "$index" "$tmp" >> "make-uninstall"
@@ -324,23 +377,39 @@ Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 			fi
 		done
 		source "$PWD/$REFERENCE"
-		
-		# Check for removal operations
+	#
+	# 	Finalize
+	#
+		# Uninstall
 		if [ ! -z "$(echo ${REMOVE[@]})" ]
 		then 	C=0
-			echo >> "make-install"
+			echo >> "make-uninstall"
 			
 			while 	item="${REMOVE[$C]}"
 				[ ! -z "$item" ]
 			do 	[ -f "$item" ] && \
-					echo "sh ./$item" >> "make-uninstall" || \
+					echo "rm -f $item" >> "make-uninstall" || \
 					echo "$item" >> "make-uninstall" #  || exit 1
 				((C++))
 			done
 		fi
 		
-		# Finalize
+		# Check for DISTCLEAN operations
+		if [ ! -z "$(echo ${CLEAN[@]})" ]
+		then 	C=0
+			echo >> "make-distclean"
+			
+			while 	item="${CLEAN[$C]}"
+				[ ! -z "$item" ]
+			do 	[ -f "$item" ] && \
+					echo "rm ./$item" >> "make-distclean" || \
+					echo "$item" >> "make-distclean" #  || exit 1
+				((C++))
+			done
+		fi
 		write_distclean >> "make-distclean"
+		
+		
 		if [ "true" = "${doRef:-false}" ]
 		then	echo >> "make-install"
 			echo "mkdir -p ${FHS[sysconfdir]} ; cp \"$REFERENCE\" \"${FHS[sysconfdir]}/$APP.conf\"" >> "make-install"
@@ -359,16 +428,28 @@ Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 				((C++))
 			done
 		fi
-		for m in install uninstall
+		for m in install uninstall distclean
 		do	echo >> "make-$m"
 			printf '%s\n' \
 				"RET=\$?" \
 				"set +x" >> "make-$m"
 		done
 		
+		# Do the PREPARE stuff, before telling to call ./make-install
+		if [ ! -z "$(echo ${PREPARE[@]})" ]
+		then 	C=0
+			while 	item="${PREPARE[$C]}"
+				[ ! -z "$item" ]
+			do 	[ -f "$item" ] && \
+					sh ./"$item" || \
+					( echo "$item" > "$TMP" ; sh -x "$TMP" )
+				((C++))
+			done
+			rm -f "$TMP"
+		fi
 		echo "echo;echo \"Finished installation of $APP\";exit \$RET" >> "make-install"	# with exit code: \$RET (0=success)\""
-		#sed s,'set -x','',g -i make-{uni,i}nstall
 		
+		#sed s,'set -x','',g -i make-{uni,i}nstall
 		sed s,'set -x',"set -x\nSYSCONFDIR=$SYSCONFDIR",g -i make-{uni,i}nstall
 		sed s,'~',"$HOME",g -i make-{uni,i}nstall
 	}
@@ -447,13 +528,13 @@ Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 	done
 	export FHS
 	prefix="${FHS[prefix]}"
-	source "$SOURCE"
+	source "$CONFIG"
 #
 #	Prepare installation script
 #
 	write_files
 	APP_REQUIRES=""
-	source "$SOURCE";missing=""
+	source "$CONFIG";missing=""
 	for req in $APP_REQUIRES;do
 		which $req 2>/dev/zero 1>&2 || missing+=" $req"
 	done
