Release 0.8

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12,9 +12,9 @@
 #			https://github.com/sri-arjuna/yassi/issues
 #
 #	Created:	2015.07.27
-#	Changed:	2015.08.05
+#	Changed:	2015.08.10
 	script_name=configure
-	script_version=0.7
+	script_version=0.8
 #
 # ------------------------------------------------------------------------
 #
@@ -38,16 +38,19 @@
 #
 #	Internal Variables
 #
-	unset FHS POST
+	unset FHS POST PRIOR
 	declare -A FHS
 	declare -a POST
+	declare -a PRIOR
 	
 	APP=""
 	doRef=false
+	doTarball=false
 	SOURCE="$0.cfg"
 	
-	index_list="prefix bindir sbindir sysconfdir datarootdir datadir docdir infodir man1dir man8dir compldir sharedstatedir localstatedir"
-	variable_list="";for i in $index_list;do variable_list+=" ${i^^}";done;variable_list+=" POST"
+	mandirs="$(echo man{1..9}dir)"
+	index_list="prefix bindir sbindir sysconfdir datarootdir datadir docdir htmldir infodir $mandirs compldir sharedstatedir localstatedir"
+	variable_list="";for i in $index_list;do variable_list+=" ${i^^}";done #;variable_list+=" PRIOR POST REMOVE"
 	source "$SOURCE"
 #
 #	Functions
@@ -56,32 +59,59 @@
 	# Prints a sample configure.cfg
 	# and exits
 		cat <<-EOF
+			APP="projectname"
+			BINDIR=bin
+			DOCDIR="docs/README.md docs/COPYING"
+			#MAN1DIR=docs/man1
+			#INFODIR=tex/\$APP.info
+			DATADIR="./templates ./extra"
+			ISSUE="https://github.com/sri-arjuna/yassi/issues"
+		EOF
+		exit 0
+	}
+	show_sample_full() {
+	# Prints a sample configure.cfg
+	# and exits
+		cat <<-EOF
 			# Project name
 			# Used for /usr/share/\$APP & /usr/share/doc/\$APP
 			APP="projectname"
+			# Used for helpscreen & tarball
+			APP_VER=0.1
+			# If set overwrites /usr/local for plain './configure' invocation
+			APP_DIR=~/local
 			
 			# Directories
 			# A plain dirname will copy all its content
 			# Single entries must not be quoted!
 			BINDIR=bin
 			# A plain filename will copy just the file
+			# The $APP.{info,html} files will be generated by the PRIOR[1|2] array entry.
 			# Multiple entries shall be quoted.
-			DOCDIR="docs/README.md docs/COPYING"
+			DOCDIR="docs/README.md docs/COPYING tex/\$APP.html"
+			MAN1DIR=docs/man1
+			INFODIR=tex/\$APP.info
 			# A dirname with a leading ./ will copy the directory
 			DATADIR="./templates ./themes"
-			MAN1DIR=docs/man
 			
-			# Specials
-			# Set true to keep the reference file in /etc/\$APP.conf
+			# Set true to install the reference file to /etc/\$APP.conf
 			doRef=false
-			# Place scripts or commands in the array
-			# variables from the \$APP_ref.conf will be available within scripts called here.
-			POST[0]=post_script1.sh
-			POST[1]="echo \"Thank you for choosing '\$APP'!\""
 			
 			# Contact
 			BUGS="your@email.com"
 			ISSUE="https://github.com/sri-arjuna/yassi/issues"
+			
+			# Specials
+			# Do things before copying/installing
+			PRIOR[0]="texi2any -o docs/tex/\$APP.info --no-split docs/tex/\$APP.texi"
+			PRIOR[1]="texi2any --html -o docs/tex/\$APP.html --no-split docs/tex/\$APP.texi"
+			
+			# Do things before copying/installing
+			POST[0]=post_script1.sh
+			POST[1]="echo \"Thank you for choosing '\$APP'!\""
+			
+			# Append this in the uninstall script.
+			REMOVE[0]="echo \"Dare you remove \$APP!\""
 		EOF
 		exit 0
 	}
@@ -89,28 +119,38 @@
 	# Prints the helpscreen
 	# and exits
 		MSG_TR_HELP="Usage:	./$script_name [options]
+Routine to configure the installation of $APP $APP_VER
+
 Options:
 	-h|--help		Shows this screen and exits
 	--version		Shows the version and exits
 	--sample		Prints a sample configure.cfg required by projects
+	--sample-full		Prints a sample configure.cfg required by projects
 	
-	--prefix DIR		Sets the prefix to DIR		(default: /usr/local)
+	--tarball		Configures ${APP:-APPNAME} and saves the folder as tarball
+	--prefix DIR		Sets the prefix to DIR		(default: ${APP_DIR:-/usr/local})
+	
 	--bindir DIR		user executeables 		(\$PREFIX/bin)
 	--sbindir DIR		admin executeables		(\$PREFIX/sbin)
 	--sysconfdir DIR	read-only single-machine data 	(\$PREFIX/etc)
-	
 	--datarootdir DIR	read-only arch.-independent data root 	(\$PREFIX/share)
+	
 	--datadir DIR		read-only architecture-independent data (\$DATAROOTDIR/${APP:-APPNAME})
 	--docdir DIR		project documentation root	(\$DATAROOTDIR/doc/${APP:-APPNAME})
-	
+	--htmldir DIR		project documentation root	(\$DOCDIR)
 	--infodir DIR		info documentation		(\$DATAROOTDIR/info)
-	--man1dir DIR		man 1 documentation 		(\$DATAROOTDIR/man/man1)
-	--man8dir DIR		man 8 documentation 		(\$DATAROOTDIR/man/man8)
+	
+	--man1dir DIR		man 1 Exe & Shell commands	(\$DATAROOTDIR/man/man1)
+		2) System calls		3) Library calls	4) Special files (eg /dev)
+		5) File formats & conventions (eg: /etc/passwd)	6) Games
+		7) Miscellaneous (eg: macros, groff(7));	8) Root commands (sbin)
+	--man9dir DIR		man 9 Kernel routines (non standard)	(\$DATAROOTDIR/man/man9)
+	
 	--compldir DIR		bash completion			(\$DATAROOTDIR/bash-completion/completions)
+	--localedir		locale-dependent data		(\$DATAROOTDIR/locale)
+	--localstatedir		modifiable single-machine data	(\$PREFIX/var)
 	
 	--sharedstatedir	modifiable architecture-independent	(\$PREFIX/com)
-	--localstatedir		modifiable single-machine data	(\$PREFIX/var)
-	--localedir		locale-dependent data		(\$DATAROOTDIR/locale)
 			
 	$( [ ! -z "$BUGS" ] && echo "Report bugs of \"$APP\" to \"$BUGS\"")
 	$( [ ! -z "$ISSUE" ] && echo "Report bugs of \"$APP\" on \"$ISSUE\"")
@@ -127,6 +167,8 @@ License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 
 This is free software; you are free to change and redistribute it.
 There is NO WARRANTY, to the extent permitted by law.
+
+Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 "
 		echo "$MSG_TR_VERSION"
 		exit 111
@@ -139,8 +181,20 @@ There is NO WARRANTY, to the extent permitted by law.
 		#
 			echo "mkdir -p \"${FHS[${1,,}]}\""
 			if [ -d "$2" ] && [ ! "./" = "${2:0:2}" ]
-			then	echo "cp -ar \"$2/\"* \"${FHS[${1,,}]}\"" | sed s,"//","/",g
-			else	echo "cp -ar \"$2\" \"${FHS[${1,,}]}\"" | sed s,"//","/",g
+			then	echo "cp -ar \"${PWD:-$(pwd)}/$2/\"* \"${FHS[${1,,}]}\" || exit 1" | sed s,"//","/",g
+			else	tmp_check="${2##*/}"
+				check_char="${tmp_check:0:1}"
+				isAsterix=$(printf '%s' "$check_char" | grep -v '*' && echo false || echo true )
+				
+				case "$isAsterix" in
+				true|false)	isAsterix=$isAsterix	;;
+				*)		isAsterix=false		;;
+				esac
+				
+				if $isAsterix
+				then 	echo "cp -ar \"${PWD:-$(pwd)}/$(dirname ${2})/\"$tmp_check \"${FHS[${1,,}]}\" || exit 1" | sed s,"//","/",g
+				else	echo "cp -ar \"${PWD:-$(pwd)}/$2\" \"${FHS[${1,,}]}\" || exit 1" | sed s,"//","/",g
+				fi
 			fi
 		}
 		write_reference() { # INDEX
@@ -154,10 +208,9 @@ There is NO WARRANTY, to the extent permitted by law.
 			INDEX="$1" ; shift
 			DEST="${FHS[${INDEX,,}]}"
 			
-			#echo "DEST: $DEST // content: $@"
-			for tr in $@
+			for tr in ${@}
 			do	case "$INDEX" in
-				SBINDIR|BINDIR|MAN[18]DIR)
+				SBINDIR|BINDIR|MAN[1-9]DIR)
 					if [ -d "${tr}" ]
 					then	for e in "./$tr/"*
 						do 	[ -d "$e" ] && \
@@ -171,9 +224,6 @@ There is NO WARRANTY, to the extent permitted by law.
 					tr="${tr/\$\{APP\}/$APP}"
 					echo "rm -f $DEST/${tr##*/}"
 					;;
-			#	INFODIR)
-			#		echo $content
-			#		;;
 				*)	[ -d "$tr" ] && \
 						echo "rm -fr $DEST/${tr##*/}" || \
 						echo "rm -f $DEST/${tr##*/}"
@@ -186,7 +236,6 @@ There is NO WARRANTY, to the extent permitted by law.
 		# Remove the files that where created
 		#
 			echo "(sleep 0.5 ; rm -f ./make-* ; rm -f $REFERENCE ) &"
-			#rm "./${script_name}.cfg"
 		}
 		
 		# Prepare script headers
@@ -202,60 +251,93 @@ There is NO WARRANTY, to the extent permitted by law.
 		done
 		>"$REFERENCE"
 		
+		# Write content of PRIOR tasks, if any
+		if [ ! -z "$(echo ${PRIOR[@]})" ]
+		then	C=0
+			echo >> "make-install"
+			while [ ! -z "${PRIOR[$C]}"  ]
+			do 	echo "${PRIOR[$C]} || exit 1" >> "make-install"
+				((C++))
+			done
+		fi
+		
 		# Search for the available variables
 		for index in $variable_list
-		do	tmp=$(awk -F= -v VAR="$index" '$1 ~ "^[^#]*" VAR "$"{print $2}' "$SOURCE")
+		do	# Expand index
+			tmp="${!index}"
+			# Count words
 			num=$(echo $tmp | wc -w)
+			
+			# Only do something if index has content count higher than 0
 			if [ "$num" -gt 0 ]
-			then	# It has content
+			then	# 'Group' different tasks 
+				echo >> "make-install"
+				echo >> "make-uninstall"
+				
+				# It has content
 				write_reference "$index" >> "$REFERENCE"
 				case "$num" in
 				1)	write_install "$index" "$tmp" >> "make-install"
 					write_uninstall "$index" "$tmp" >> "make-uninstall"
-					#write_reference "$index" >> "$REFERENCE"
 					;;
 				*)	for s in $(echo "$tmp"|sed s,\",,g)
 					do 	write_install "$index" "$s" >> "make-install"
 						write_uninstall "$index" "$s" >> "make-uninstall"
-						#write_reference "$index" >> "$REFERENCE"
 					done
 					;;
 				esac
 			fi
 		done
 		
-		# Check for post operations
-		if [ ! -z "$(echo ${POST[@]})" ]
+		# Check for removal operations
+		if [ ! -z "$(echo ${REMOVE[@]})" ]
 		then 	C=0
-			while 	item="${POST[$C]}"
+			echo >> "make-install"
+			
+			while 	item="${REMOVE[$C]}"
 				[ ! -z "$item" ]
 			do 	[ -f "$item" ] && \
-					echo "sh ./$item" >> "make-install" || \
-					echo "$item" >> "make-install"
+					echo "sh ./$item || exit 1" >> "make-uninstall" || \
+					echo "$item || exit 1" >> "make-uninstall"
 				((C++))
 			done
 		fi
 		
 		# Finalize
 		write_distclean >> "make-distclean"
-		if $doRef 
-		then	echo "mkdir -p ${FHS[sysconfdir]} ; cp $REFERENCE ${FHS[sysconfdir]}/$APP.conf" >> "make-install"
+		if [ "true" = "${doRef:-false}" ]
+		then	echo >> "make-install"
+			echo "mkdir -p ${FHS[sysconfdir]} ; cp \"$REFERENCE\" \"${FHS[sysconfdir]}/$APP.conf\"" >> "make-install"
 			echo "rm -f ${FHS[sysconfdir]}/$APP.conf" >> "make-uninstall"
 		fi
 		for m in install uninstall
-		do	printf '%s\n' \
+		do	echo >> "make-$m"
+			printf '%s\n' \
 				"RET=\$?" \
 				"set +x" >> "make-$m"
 		done
-		echo "echo \"Finished installation of $APP with exit code: \$RET (0=success)\"" >> "make-install"
+		
+		# Check for post operations, letter better here, than with 'set -s'
+		if [ ! -z "$(echo ${POST[@]})" ]
+		then 	C=0
+			echo >> "make-install"
+			while 	item="${POST[$C]}"
+				[ ! -z "$item" ]
+			do 	[ -f "$item" ] && \
+					echo "sh ./$item || exit 1" >> "make-install" || \
+					echo "$item || exit 1" >> "make-install"
+				((C++))
+			done
+		fi
+		
+		echo "echo;echo \"Finished installation of $APP with exit code: \$RET (0=success)\"" >> "make-install"
 	}
 #
 #	Get options
 #
-	# -a|--alternative ; to allow longoptions with a single leading '-'
 	GETOPT=$(getopt \
 		--options	"h" \
-		--longoptions	"help,version,sample,bindir:,sbindir:,prefix:,datarootdir:,datadir:,infodir:,man1dir:,man8dir:,localedir:,docdir:,compldir:,sharedstatedir:,localstatedir:,localedir:" \
+		--longoptions	"help,version,sample,sample-full,tarball,bindir:,sbindir:,prefix:,datarootdir:,datadir:,infodir:,man[1-9]dir:,localedir:,docdir:,compldir:,sharedstatedir:,localstatedir:,localedir:" \
 		--name 		"${0##*/}" -- "${@}"
 	)
 	eval set -- "$GETOPT"
@@ -264,16 +346,19 @@ There is NO WARRANTY, to the extent permitted by law.
 		-h|--help)	show_help	;;
 		--version)	show_version	;;
 		--sample)	show_sample	;;
+		--sample-full)	show_sample_full;;
 		--prefix|--bindir|--sbindir|--datarootdir|--datadir|\
-		--infodir|--sysconfdir|--man1dir|--man8dir|--docdir|\
+		--infodir|--sysconfdir|--man[1-9]dir|--docdir|--htmldir|\
 		--compldir|--sharedstatedir|--localstatedir|--localedir)
 				FHS["${1/--}"]="$2"
 				shift 2		;;
+		--tarball)	doTarball=true
+				shift 		;;
 		--)		shift ; break	;;
 		esac
 	done
-	[ -z "$APP" ] && exit 1
-	REFERENCE="${APP}_ref.conf"
+	[ -z "$APP" ] && echo "Missing APP name..." && exit 1
+	REFERENCE="${APP}_dirs.conf"
 #
 #	Prepare paths
 #
@@ -282,9 +367,9 @@ There is NO WARRANTY, to the extent permitted by law.
 		tmp="${FHS[$index]}"
 		if [ -z "$tmp" ]
 		then	case "$index" in
-			prefix)		tmp="/usr/local"		;;
-			bindir)		tmp="${FHS[prefix]}/bin"	;;
-			sbindir)	tmp="${FHS[prefix]}/sbin"	;;
+			prefix)		tmp="${APP_DIR:-/usr/local}"	;;
+			"bindir")	tmp="${FHS[prefix]}/bin"	;;
+			"sbindir")	tmp="${FHS[prefix]}/sbin"	;;
 			sysconfdir)	case "${FHS[prefix]}" in
 					"/"|"/usr")
 						tmp="/etc"		;;
@@ -293,10 +378,10 @@ There is NO WARRANTY, to the extent permitted by law.
 			datarootdir)	tmp="${FHS[prefix]}/share"	;;
 			datadir)	tmp="${FHS[datarootdir]}/$APP"	;;
 			infodir)	tmp="${FHS[datarootdir]}/info"	;;
-			man1dir)	tmp="${FHS[datarootdir]}/man/man1" ;;
-			man8dir)	tmp="${FHS[datarootdir]}/man/man8" ;;
+			man[0-9]dir)	tmp="${FHS[datarootdir]}/man/${index:0:4}" ;;
 			localedir)	tmp="${FHS[datarootdir]}/locale" ;;
 			docdir)		tmp="${FHS[datarootdir]}/doc/$APP" ;;
+			htmldir)	tmp="${FHS[docdir]}" ;;
 			compldir)	tmp="${FHS[datarootdir]}/bash-completion/completions"	;;
 			sharedstatedir)	tmp="${FHS[prefix]}/com"	;;
 			localstatedir)	tmp="${FHS[prefix]}/var"	;;
@@ -311,8 +396,19 @@ There is NO WARRANTY, to the extent permitted by law.
 #
 #	Output
 #
-	echo
-	echo "The installation script has been configured to ${FHS[prefix]}."
-	echo "To install \"$APP\" now, please execute: su -c \"./make-install\""
-	echo
+	if $doTarball
+	then	tmp_p=$(pwd)
+		tmp_dir=$(dirname $tmp_p)
+		[ -z "$APP_VER" ] && \
+			VERSION="" || \
+			VERSION="_${APP_VER}"
+		tarball="../${APP}$VERSION.tar.gz"
+		tar -acf "$tarball" *
+		mv "$tarball" . && \
+			echo "Successfully created tarball ${tarball##*/}!"
+	else	echo
+		echo "The installation script has been configured to ${FHS[prefix]}."
+		echo "To install \"$APP\" now, please execute: su -c \"./make-install\""
+		echo
+	fi
 	exit
